apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatwithpdf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/durgax04/ops.git'
    targetRevision: main
    path: pdfchatapp
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
